version: '3.7'

services:
  composer:
    image: composer:1.6
    user: ${CURRENT_UID}
    volumes:
      - .:/app
    command: composer install --ignore-platform-reqs --no-scripts
  php:
    image: php:7.2-cli-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: php index.php